version: '3.8'

services:
  hurobot-psql:
    image: postgres:latest
    container_name: hurobot-psql
    hostname: hurobot-psql
    environment:
      POSTGRES_USER: hurobot
      POSTGRES_PASSWORD: hurobot
      POSTGRES_DB: hurobot
    volumes:
      - ./psql-init:/docker-entrypoint-initdb.d
      - ./psql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: on-failure
